---
title: "Etheme 7-Regles d'association"
author: "Thomas Laurent"
date: "19/03/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(arules)
library(arulesViz)

```


```{r}
#Import des donnees
 data(Groceries)
summary(Groceries)
```

```{r}
itemFrequencyPlot(Groceries,topN=20,type="absolute")
```

```{r}
rules <- apriori(Groceries, parameter = list(supp = 0.001, conf = 0.8))
options(digits=2)
inspect(rules[1:5])
rules<-sort(rules, by="confidence", decreasing=TRUE)
inspect(rules[1:5])
```

```{r}
#Parametrer le maximum du nombre d'items#
rules <- apriori(Groceries, parameter = list(supp = 0.001, conf = 0.8,maxlen=3))
inspect(rules[1:5])


library(arulesViz)
plot(rules,method="graph",interactive=TRUE,shading=NA)
```

```{r}
#Ciblage des items#
rules<-apriori(data=Groceries, parameter=list(supp=0.001,conf = 0.08),
                 appearance = list(default="lhs",rhs="whole milk"),
               control = list(verbose=F))
rules<-sort(rules, decreasing=TRUE,by="confidence")
inspect(rules[1:5])

rules<-apriori(data=Groceries, parameter=list(supp=0.001,conf = 0.15,minlen=2),
               appearance = list(default="rhs",lhs="butter"),
               control = list(verbose=F))
rules<-sort(rules, decreasing=TRUE,by="confidence")
inspect(rules[1:5])
```

#Donnees Titanic

```{r}
titanic_ar <- read.delim("/Users/thomaslaurent/Documents/Cours-M2/Data-Mining2/Etheme7/titanic.txt", dec=",")
str(titanic_ar)
titanic_ar$Age = as.character(titanic_ar$Age)
c_idx <- which(as.numeric(titanic_ar$Age) < 20)
a_idx <- which(as.numeric(titanic_ar$Age) >= 20)
na_idx <- which(is.na(titanic_ar$Age))
titanic_ar$Age[c_idx] <- "Child"
titanic_ar$Age[a_idx] <- "Adult"
titanic_ar$Age[na_idx] <- "Unknown"
# Convertir les attributs en facteur
titanic_ar$Age <- as.factor(titanic_ar$Age)
titanic_ar$Survived <- as.factor(titanic_ar$Survived)
```

```{r}
rules <- apriori(titanic_ar)
inspect(rules)
```

```{r}
rules <- apriori(titanic_ar, parameter = list(minlen = 3,
                                              support = 0.1, conf = 0.8),
                                              appearance = list(rhs = c("Survived=0", "Survived=1"), default="lhs"))
rules<-sort(rules, decreasing=TRUE,by="confidence")
inspect(rules)
```

```{r,fig.height=8,fig.width=8}
plot(rules)
plot(rules, method="scatterplot")
plot(rules, method="graph", control=list(type = "items", alpha = 1))
plot(rules, method="paracoord", control=list(reorder=TRUE))
```

